string exename;//程序名 
string inname;//输入文件名 
string outname;//输出文件名 
int from;//文件开始编号 
int to;//文件结束编号
bool exenameset;//程序名已设置 
bool innameset;//输入文件名已设置 
bool outnameset;//输出文件名已设置 
bool fromset;//文件开始编号已设置 
bool toset;//文件结束编号已设置
